title: RayJoin
logo: /assets/img/rayjoin.webp
description: Fast and Precise Spatial Join on RT Cores
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github:
  zip_url: https://github.com/pwrliang/RayJoin/archive/refs/heads/main.zip
  repository_url: https://github.com/pwrliang/RayJoin